from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from app.core.config import settings
from app.core.rate_limiter import gemini_limiter
from app.database import db
import json

# ── Gemini 2.5 Flash ──────────────────────────────────────────────────────────
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash-preview-04-17",
    google_api_key=settings.GEMINI_API_KEY,
    temperature=0.3,
)

# ── System prompt ─────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are UCRIS Assistant, an expert credit risk analyst AI.
You help credit officers understand customer risk profiles, stress levels,
and escalation predictions generated by the UCRIS system.

Always ground your answers in the data provided. Be concise and professional.
If asked about a specific customer, reference their actual prediction data.
If asked general questions, explain UCRIS concepts clearly.

Context from database:
{context}
"""


# ── Narrative generation ──────────────────────────────────────────────────────

async def generate_narrative(prediction: dict, customer: dict) -> str:
    """Generate a natural language explanation for a prediction."""

    # Rate limit check before Gemini call
    await gemini_limiter.acquire()

    shap_text = "\n".join([
        f"- {f['feature']}: {f['shap_value']:+.3f} (value: {f['value']:.3f})"
        for f in prediction["shap_factors"][:3]
    ])

    escalation_status = "Escalating" if prediction["escalation_flag"] else "Stable"

    prompt = ChatPromptTemplate.from_messages([
        ("system", """You are a credit risk expert. Write a brief professional
        2-3 sentence explanation for a credit officer about why this customer
        has been flagged. Be specific about the behavioral drivers."""),
        ("human", """Customer: {customer_ref}
Stress Level: {stress_label} (confidence: {confidence})
Escalation: {escalation_status} ({escalation_prob:.1%} probability)
Recommended Action: {recommended_action}

Top behavioral drivers (SHAP):
{shap_text}

Write a clear explanation for the credit officer.""")
    ])

    chain = prompt | llm | StrOutputParser()
    return await chain.ainvoke({
        "customer_ref":       customer.get("customer_ref", "Unknown"),
        "stress_label":       prediction["stress_label"],
        "confidence":         prediction["confidence"],
        "escalation_status":  escalation_status,
        "escalation_prob":    prediction["escalation_prob"],
        "recommended_action": prediction["recommended_action"],
        "shap_text":          shap_text,
    })


# ── RAG Chat ──────────────────────────────────────────────────────────────────

async def chat_with_context(message: str, customer_id: str = None) -> dict:
    """RAG chatbot — retrieves relevant data from NeonDB and answers."""

    # Rate limit check before Gemini call
    await gemini_limiter.acquire()

    context_parts = []

    # If customer_id provided, fetch their full profile
    if customer_id:
        customer = await db.customer.find_unique(
            where={"id": customer_id},
            include={
                "features": True,
                "predictions": {
                    "take": 5,
                    "order_by": {"predicted_at": "desc"}
                }
            }
        )
        if customer:
            context_parts.append(f"CUSTOMER PROFILE: {customer.customer_ref}")
            context_parts.append(f"Age: {customer.age}, Education: {customer.education}")
            context_parts.append(f"Credit Limit: {customer.limit_bal:,}")

            if customer.features:
                f = customer.features
                context_parts.append(f"""BEHAVIORAL FEATURES:
- Avg Utilization: {f.avg_utilization:.2%}
- Utilization Change: {f.util_change:+.3f}
- Pay Delay Trend: {f.pay_delay_trend:+.3f}
- Consecutive Delays: {f.consecutive_delays}
- Avg Repay Ratio: {f.avg_repay_ratio:.2%}""")

            if customer.predictions:
                p = customer.predictions[0]
                context_parts.append(f"""LATEST PREDICTION:
- Stress: {p.stress_label} (L:{p.stress_prob_low:.2%} M:{p.stress_prob_med:.2%} H:{p.stress_prob_high:.2%})
- Escalation: {"Yes" if p.escalation_flag else "No"} ({p.escalation_prob:.2%})
- Action: {p.recommended_action}
- SHAP Factors: {json.dumps(p.shap_factors, indent=2)}""")

    # Portfolio summary for general questions
    total_customers = await db.customer.count()
    high_stress     = await db.prediction.count(where={"stress_label":       "High"})
    escalating      = await db.prediction.count(where={"escalation_flag":    1})
    restructure     = await db.prediction.count(where={"recommended_action": "Restructure"})

    context_parts.append(f"""PORTFOLIO SUMMARY:
- Total Customers: {total_customers}
- High Stress: {high_stress}
- Escalating: {escalating}
- Needs Restructuring: {restructure}""")

    context = "\n\n".join(context_parts)

    prompt = ChatPromptTemplate.from_messages([
        ("system", SYSTEM_PROMPT),
        ("human", "{question}")
    ])

    chain = prompt | llm | StrOutputParser()
    answer = await chain.ainvoke({
        "context":  context,
        "question": message,
    })

    return {
        "answer":  answer,
        "sources": context_parts[:3],
    }